change validation to regex

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -21,15 +21,15 @@ inputs:
     default: true
     description: (Decode) Fail if the JWT signing cannot be verified.
     type: boolean
-  enable-mask-jwt: 
+  enable-mask-jwt:
     default: false
     description: (Decode/Encode) Enable masking of entire JWT in Actions output.
     type: boolean
-  enable-mask-signature: 
+  enable-mask-signature:
     default: true
     description: (Decode/Encode) Enable masking of JWT signature in Actions output.
     type: boolean
-  headers:
+  header:
     default: |
       alg: ${ALGORITHM}
       typ: JWT
@@ -52,9 +52,9 @@ outputs:
   algorithm:
     description: Signing algorithm.
     value: ${{ fromJSON(steps.decode.outputs.json).algorithm }}
-  headers:
-    description: Decoded headers in JSON.
-    value: ${{ toJSON(fromJSON(steps.decode.outputs.json).headers) }}
+  header:
+    description: Decoded header in JSON.
+    value: ${{ toJSON(fromJSON(steps.decode.outputs.json).header) }}
   json:
     description: Decoded JWT object in JSON format.
     value: ${{ steps.decode.outputs.json }}
@@ -85,7 +85,7 @@ runs:
         ALGORITHM: ${{ inputs.algorithm }}
         ENABLE_MASK_JWT: ${{ inputs.enable-mask-jwt == 'true' && 'true' || 'false' }}
         ENABLE_MASK_SIGNATURE: ${{ inputs.enable-mask-signature == 'true' && 'true' || 'false' }}
-        HEADERS: ${{ inputs.headers }}
+        HEADER: ${{ inputs.header }}
         JQ_LIB_PATH: ${{ github.action_path }}
         PAYLOAD: ${{ inputs.payload }}
         SECRET: ${{ inputs.secret }}
@@ -93,23 +93,23 @@ runs:
       if: inputs.payload != ''
       run: |
         # JWT - Encode Token
-        HEADERS=$(yq -o json --expression 'with_entries(.value |= envsubst)' <<<"${HEADERS}" | jq -c)
+        HEADER=$(yq -o json --expression 'with_entries(.value |= envsubst)' <<<"${HEADER}" | jq -c)
         PAYLOAD=$(yq -o json <<<"${PAYLOAD}" | jq -c)
         if '${{ env.ACTIONS_STEP_DEBUG == 'true' && 'true' || 'false' }}' ; then
-          echo -e "::group::Debug - headers\n${HEADERS}\n::endgroup::"
+          echo -e "::group::Debug - header\n${HEADER}\n::endgroup::"
           echo -e "::group::Debug - payload\n${PAYLOAD}\n::endgroup::"
         fi
         JWT_UNSIGNED=$(
           jq -n -r -L "$JQ_LIB_PATH" \
-            --arg headers "$HEADERS" \
+            --arg header "$HEADER" \
             --arg payload "$PAYLOAD" \
             ' include "jwt";
-              [($headers | url_safe_base64_encode), ($payload | url_safe_base64_encode)]
+              [($header | url_safe_base64_encode), ($payload | url_safe_base64_encode)]
               | join(".")
             '
         )
         SIGNATURE_ARGS=()
-        if '${{ inputs.SECRETS == '' && 'false' || 'true' }}' ; then 
+        if '${{ inputs.SECRETS == '' && 'false' || 'true' }}' ; then
           SIGNATURE_ARGS=(-hmac "$SECRET")
         fi
         SIGNATURE=$(
@@ -145,15 +145,26 @@ runs:
       id: decode
       run: |
         # JWT - Decode/Verify Token
+        set -x
         if $ENABLE_MASK_JWT ; then
           echo "::add-mask::${JWT}"
         fi
+
+        JWT_IS_VALID=$(
+          jq -n -r -L "$JQ_LIB_PATH" --arg jwt "$JWT" \
+            'include "jwt"; $jwt | validate'
+        )
+        if [ "$JWT_IS_VALID" != 'true' ] ; then
+          echo '::error title=JWT Is Invalid::The JWT provided or generated is invalid (not parseable).'
+          exit 1
+        fi
+
         JWT_UNSIGNED=$(
           jq -n -r -L "$JQ_LIB_PATH" --arg jwt "$JWT" \
             'include "jwt"; $jwt | decode_raw.unsigned'
         )
         SIGNATURE_ARGS=()
-        if '${{ inputs.SECRETS == '' && 'false' || 'true' }}' ; then 
+        if '${{ inputs.SECRETS == '' && 'false' || 'true' }}' ; then
           SIGNATURE_ARGS=(-hmac "$SECRET")
         fi
         SIGNATURE=$(
